report: "html"
modules:
  discover:
    RHOST: "127.0.0.1"
    PORT: 502
  finduid:
    RHOST: "127.0.0.1"
    UID_FROM: 0
    UID_TO: 20
    THREADS: 10
  synscan:
    RHOST: "127.0.0.1"
    PORT: "500-10000"
    THREADS: 10
