report: "html"
modules:
  discover:
    RHOSTS: "127.0.0.1-127.0.0.255"
    PORT: 502
    THREADS: 10
    modules:
      finduid:
        UID_FROM: 0
        UID_TO: 10
  synscan:
    RHOST: "127.0.0.1"
    PORT: "500-1000"
    THREADS: 5
